### ISSUE TITLE
Blocked topic

### ISSUE THREAD

**Issue by abarbuc** [thredded/thredded#795] opened 2019-03-02 18:03 UTC
Hi, 

This may be a basic question and from my search in the previous topics I could not find an answer. Apologies if it was covered and I am missing it. 

When a moderator blocks a topic how can this be displayed to the author? I see other authors do not see it and the moderator sees it as blocked but for the original author displays as normal.  Also is there a way when blocked to provide feedback why it was blocked?

Thank you for the great functionality as well, great work.

**Comment by glebm** [comment] 2019-03-02 20:54
> I see other authors do not see it and the moderator sees it as blocked but for the original author displays as normal.

This is intentional as blocking is mainly intended for spam.

If you want to add a setting for this, feel free to send a PR.

Note that if a user is "pending moderation" and you block their first topic, all their subsequent topics are blocked automatically (this is not the case if the user is "approved").

> Also is there a way when blocked to provide feedback why it was blocked?

Nothing specific to blocking. You can simply reply to the topic though.

**Comment by abarbuc** [comment] 2019-03-03 02:10
Thank you for the prompt reply and the clarifications. 

Is there to reply to a single blocked post? I see there is a quote option but that does not maintain the blocked properties of the initial message. 

I have a second issue with creating topics. Locally everything seems to work ok in terms of creating Topics. But once deployed I can create one topic (if the Browser History is cleared) and I can not create a second topic. In the developer tools console I see these errors:

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https: 'nonce-pDnQi0nWruwDOwTeEY31EQ=='". Either the 'unsafe-inline' keyword, a hash ('sha256-7cGCBh58ly6eVRh4wmX6H0WwhYbFAKpZaPiOoKa+nEE='), or a nonce ('nonce-...') is required to enable inline execution.
> 
> An invalid form control with name='topic[content]' is not focusable.
> 

The Chrome version I am testing with is Version 72.0.3626.119. I was also testing in Firefox 65.0.1  and same thing. 

Thank you for taking the time to answer.

**Comment by glebm** [comment] 2019-03-03 03:54
> Refused to execute inline script because it violates the following Content Security Policy directive

It's what it says, you're setting a CSP header that doesn't allow Thredded to execute its inline script. Add the hash as above to your CSP header.

> I can not create a second topic

Likely caused by the above.

> An invalid form control with name='topic[content]' is not focusable.

I'm guessing this will be fixed once you fix the CSP header.

**Comment by glebm** [comment] 2019-03-03 15:57
For the CSP issue, I've added nonce to the inline scripts on master. Try it out.

You need 2 things so that it works:

1. You have Turbolinks support in your CSP config:

```ruby
    config.content_security_policy_nonce_generator = ->(request) {
      if request.env['HTTP_TURBOLINKS_REFERRER'].present?
        # Turbolinks nonce CSP support.
        # See https://github.com/turbolinks/turbolinks/issues/430
        request.env['HTTP_X_TURBOLINKS_NONCE']
      else
        SecureRandom.base64(16)
      end
    }
```

2. You have `<%= csp_meta_tag %>` in your `<head>`.

**Comment by abarbuc** [comment] 2019-03-04 16:34
You rock!! It all works fine now. Thank you very much.

**Closed** 2019-06-05 08:07 UTC
