### ISSUE TITLE
Moderator with limited board privileges can moderate all users

### ISSUE THREAD

**Issue by leenyburger** [thredded/thredded#731] opened 2018-09-26 12:06 UTC
I'm not sure if this is a bug or intentional: 
I have set up moderators with certain permissions in `def thredded_can_moderate_messageboards`
Works great! However, in the nav bar the `users` link allows any moderator to moderate ALL users. If the moderator is limited to only moderating certain messageboards, they should only be able to moderate users that have permissions on those messageboards. Suggestion : provide a `thredded_can_moderate_users` method exposed in the users model. 
Right now I'm patching 
```module Thredded
        class ModerationController
          def moderate_user
          end
       end
     end
``` 
with limited success

**Comment by glebm** [comment] 2018-09-26 19:49
Closing as a duplicate of #732

**Closed by glebm** 2018-09-26 19:49 UTC
