### ISSUE TITLE
Single topic list containing topics from multiple boards

### ISSUE THREAD

**Issue by chrisalley** [thredded/thredded#662] opened 2017-12-01 22:27 UTC
As an option, it would be great to have a single topic list containing topics from all of the boards, similar the main topic list in Discourse. This would prevent the user from having to navigate into multiple board views to see all of the updated topics since their last visit.

**Comment by glebm** [comment] 2017-12-02 12:52
This is a duplicate of #604 and there is an unfinished implementation in #608.

**Closed** 2017-12-02 12:53 UTC
Labels: duplicate
