### ISSUE TITLE
SystemStackError (stack level too deep): - on a pluck

### ISSUE THREAD

**Issue by netpenthe** [thredded/thredded#842] opened 2019-10-26 09:35 UTC
I've been trying to get thredded going for the last week.

I'm running ruby-2.3.3 and rails 4.2.6 (also tried 4.2.11).

Thredded 0.16.0+ fails to load a page of my app (not /forum) with the below error:
`SystemStackError (stack level too deep):`

The line is this:
` Design.where(user_id: User.where(department_id: id).pluck(:id))`

This is not on the /forum page, but on any page or if I try to do this pluck from the command line. NOTE: the pluck has **nothing** to do with Thredded

I tried going back to 0.15.5 and the pluck worked fine, I checked the diff between 0.16.14 and 0.15.5 and saw that starting from 0.16.0 pluck is altered/patched:
```
# lib/thredded/arel_compat.rb 

if Rails::VERSION::MAJOR == 4
#  Make `pluck` compatible with Arel.
```

I tried removing the whole block below and **now things work** (but I don't know what else I'm breaking):
```
if Rails::VERSION::MAJOR == 4
 #  Make `pluck` compatible with Arel.
  require 'active_record/relation'
  ActiveRecord::Relation.prepend(Module.new do
    def pluck(*column_names)
      super(*column_names.map do |n|
        if n.is_a?(Arel::Node)
          Arel.sql(n.to_sql)
        elsif n.is_a?(Arel::Attributes::Attribute)
          n.name
        else
          n
        end
      end)
    end
  end)
end
```

Is that 'pluck compatibilty' block breaking other things by any chance? (sorry i don't know enough about Arel to know what this is doing!)

**Comment by netpenthe** [comment] 2019-11-22 00:12
bump?

**Comment by glebm** [comment] 2019-11-22 08:38
Try updating to Rails 4.2.11.1

**Comment by netpenthe** [comment] 2019-12-19 12:01
no luck :/
i didn't need to run the upgrade as it is a new install.

I upgraded to Rails 4.2.11.1 and Ruby 2.4.9 and i'm still getting the "stack level too deep" error :/

**Comment by glebm** [comment] 2019-12-19 13:51
Removing that code would break things like this:
https://github.com/thredded/thredded/blob/243bf48f70668f35b208006b364da65c6147b819/app/models/concerns/thredded/user_topic_read_state_common.rb#L33

I guess you'll have to go step-by-step with a debugger to figure out what's wrong.

**Comment by netpenthe** [comment] 2019-12-20 06:58
i'm willing to do this - do you have any suggestions on how to get started? I have a LOT of gems, i am guessing one is conflicting.

Any idea how i go about isolating this? 
would it be better to just start from a clean 4.2.11.1 / 2.4.9 app and gradually add gems in?
or can i somehow debug thredded?

**Comment by timdiggins** [comment] 2019-12-21 09:18
Hi @netpenthe, 

here's a few suggestions for how to debug

1) Use a ruby debug tool of some kind - e.g. built into your ide (put a breakpoint at def pluck and see what the callstack looks like and take it from there)
2) Edit the thredded files and put in a `puts` statement to print out arguments, or [use pry to halt execution](https://github.com/pry/pry#runtime-invocation) - to stop messing yourself up in future, you may use a local cloned copy of thredded rather than editing the installed files (https://bundler.io/v1.16/bundle_config.html#LOCAL-GIT-REPOS)
3) Or as you say you could try a more blackbox approach and see if you can identify what is the problem, if you think it is a gem conflict: I'd start with a totally vanilla rails app, add thredded, then add all of your gems, and see if you can reproduce -- if you can then you can progress by removing half the gems and see if you can isolate which block of gems is causing it, narrowing it down. 

If you get to a point where you can narrow it down a bit and have a public repo which demonstrates the problem (e.g. via 3), add a link to the repo here.

**Comment by netpenthe** [comment] 2019-12-22 04:42
Thanks @glebm and @timdiggins 

I found the problem - newrelic was conflicting with it as it was doing an `alias_method` for `pluck` which apparently can conflict with Thredded's `prepend` of `pluck`

I just grepped through my gemset library for `alias_method` and saw a bunch of things in the newrelic gem.

Hope this saves someone a bunch of time in the future.
Also see: [https://blog.newrelic.com/engineering/ruby-agent-module-prepend-alias-method-chains/]

**Comment by glebm** [comment] 2019-12-22 05:37
@netpenthe Thanks for the investigation! I've opened https://github.com/thredded/thredded/pull/848 as a potential fix for this issue.

**Closed** 2019-12-22 14:11 UTC

**Comment by netpenthe** [comment] 2019-12-22 22:05
you guys are very efficient!
