### ISSUE TITLE
Not autoloading / reloading is a pain

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#478] opened 2016-11-18 10:49 UTC
To fix rails admin (https://github.com/thredded/thredded/issues/280) 🎉 , we've stopped auto_loading lib (https://github.com/thredded/thredded/commit/181dfa1a9ef3e62018d6385fa7f6ad013ad8085c) 

I worry that having a mixture of autoloaded and non-autoloaded paths is likely to cause us problems -- a proliferation of explicit requires and require_dependency (for non-autoload and autoload respectively -- but easy to get this wrong when it's all Thredded code) which are then confusing.
We already have loads of explicit requires in the spec files. 

Also it's just a hassle to not auto reload.

But we could just move most of our /lib code to an /app/lib directory (autoloaded) and only leave the code in /lib that we are either planning to move out to a plugin anyway (a kind of halfway house), or is a generator or template or rake/thor task or the engine itself

**Comment by timdiggins** [comment] 2016-11-18 10:49
@glebm thoughts on this?

**Comment by glebm** [comment] 2016-11-18 12:18
Here are some thoughts per file:
1. `content_formatter.rb` - I think this must stay in lib, because its class attributes are modified in the initializers outside of `config.to_prepare` and these modification would be lost if it is reloaded.
2. `html_pipeline/` - can stay in lib, because it's a dependency of `content_formatter.rb` that isn't reloaded.
3. `view_hooks/` - can stay in lib or move to `app/view_hooks`.
4. `database_seeder.rb` - Must stay in lib, because we do not want to eager load it in production.
5. `errors.rb` - Must stay in lib because other files in lib depend on it.
6. `search_parser.rb`, `topics_search.rb` - These are actually form models / scopes, so should go into `app/`. But we're not changing these files much at all, so can stay in lib for now.

So, out of the current files in lib, only `view_hooks/`, `search_parser.rb`, and `topics_search.rb` can be moved to `app/`. The notifiers code should go into `app/notifiers/thredded`.

**Comment by timdiggins** [comment] 2016-11-18 12:33
SGTM. @glebm -- will get the notifier stuff done in #442 and then we can move the other ones as we necessary (given we have a plan, we don't have to do it all at once)

My feeling is we should try to minimize `require_dependency` (and require, though typically these are needed)-- they can proliferate without end.  To that end we should remove them as we move files.

My understanding for the distinction is:

* always use require for non-autoloaded files (and thus non-reloadable modules)
* always use require_dependency for autoloaded paths (but be skeptical about why we need them -- almost always an indication of something going wrong (but occasionally something dynamic like STI) http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#require-dependency)

and

* when requiring non-autoloaded files from autoloaded files: I think this should use `require` however I note we are using `require_dependency` in the code for this. moving things to app/ should mean we can remove the line altogether.

**Comment by glebm** [comment] 2016-11-19 21:59
@timdiggins 

An additional edge-case I've just found:

Looks like we cannot use `require` to require non-autoloaded files from autoloaded files.
When an autoloaded file gets reloaded, all of the constants defined by that file get removed.

Say file A is autoloaded and it requires the non-autoloaded file R via `require`. Also, it is the first time R is required. When A is loaded, Rails will [remember](https://github.com/rails/rails/blob/e491b2c06329afb3c989261a2865d2a93c8b84b8/activesupport/lib/active_support/dependencies.rb#L475-L479) all of the constants defined by loading A, and that includes R.

So, when A is then unloaded before a reload, R will get [removed](https://github.com/rails/rails/blob/e491b2c06329afb3c989261a2865d2a93c8b84b8/activesupport/lib/active_support/dependencies.rb#L561). When A is then loaded again, the `require` will be a no-op, and R will not get loaded.

Therefore, when requiring from an auto-loaded file, `require_dependency` must always be used even if requiring a non-autoloaded file. However, that will turn the non-autoloaded file into a reloadable one, which may have side-effects. Therefore, **autoloaded files cannot require non-autoloaded files at all**.

**Comment by timdiggins** [comment] 2016-11-19 22:24
@glebm are you sure about this? I'm pretty sure this is wrong. (e.g. `require set` very normal in https://github.com/thredded/thredded/pull/483/commits/2abd15b23c8529eaa949504ddaefb8ead259024d#diff-1b94ad79f70c2a58500a453a80391139 -- feels very wrong to move it to thredded.rb, where we then lose why we have added the dependency at all -- we will never end up removing it)

**Comment by glebm** [comment] 2016-11-19 22:26
On `require_dependency`:

This is for production mode. As I understand, in production eager loading works as follows:

1. Call `eager_load!` on all `Rails.application.config.eager_load_namespaces`. This will call `eager_load!` on `Thredded::Engine`. https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/railties/lib/rails/application/finisher.rb#L67
2. `Thredded::Engine.eager_load!` will `require_dependency` for every file in the engine's `autoload_paths`. https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/railties/lib/rails/engine.rb#L472

This means that we indeed do not ever need to call `require_dependency` to load an autoloaded path. However, the way constant resolution works with autoloading, we may need to use absolute module names for it to not conflict with main_app in development mode.

**Comment by timdiggins** [comment] 2016-11-19 22:26
PS -- your findings are at complete discord with my [understandings above](https://github.com/thredded/thredded/issues/478#issuecomment-261521752). Unless this is only to do with engines...

**Comment by glebm** [comment] 2016-11-19 22:31
> are you sure about this? I'm pretty sure this is wrong.

It is easily reproducible! I came across this because it actually broke for me.
You can reproduce it by reverting https://github.com/thredded/thredded/commit/0a5ba36c8053a1b36eafacfa18a94fcd7fb8ed8f, then going to any page (e.g. preferences), changing the controller for that page, and then reloading.

This will not be reproducible with `require 'set'` because the autoloaded file is never the first one to call `require 'set'`.

**Comment by glebm** [comment] 2016-11-19 22:34
> PS -- your findings are at complete discord with my understandings above. Unless this is only to do with engines...

This seems to apply everywhere because a regular Rails app is just a non-isolated engine with some extra methods. After reading the source code linked above I'm pretty convinced.

**Comment by timdiggins** [comment] 2016-11-19 22:39
Ok, but this is just that you have to restart your dev server occasionally when you change some files ... and if you move most of the files that are changing into autoloaded paths the problem goes away. Or use guard-rails with a decent Guardfile.

It feels wrong to make the code harder to read and reason about (especially about where dependencies are occurring), when it's easier to make them autoloadable and hence reloadable... or simply you have to re start the server. (I don't think your reasoning is correct for gems / libraries required from reloadable files, but I will look more into it).

er, but I'm logging out for now. Will think more about it tomorrow

**Comment by glebm** [comment] 2016-11-19 22:51
@timdiggins Gnight!

> It feels wrong to make the code harder to read and reason about (especially about where dependencies are occurring), when it's easier to make them autoloadable and hence reloadable...

I agree, however I'm first trying to understand fully how autoloading works, then make the current code correct. The next step is to move as much as possible into autoloaded paths.

I think I might write a blog post titled "How Rails autoloading *really* works".

**Comment by timdiggins** [comment] 2016-11-19 23:07
> I think I might write a blog post titled "How Rails autoloading really works".
@glebm  good idea!

Although I said I was off, actually, I couldn't quite resist looking a bit more into this. with a vanilla new rails app and adding in `gem 'faker', require: false` to the Gemfile, and a posts controller with the following bits:

```ruby
require 'faker'

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts/new
  def new
    @post = Post.new
    # @post.title = Faker::Hipster.sentence
    @post.title = Faker::Superhero.name
  end

...
```

Now if I view this in a browser and move the comment line from Faker::Hipster.sentence to the next line, and reload the browser, yes, I see a change. No Faker doesn't get booted out.

So I think we should be ok with other gems required explicitly from an autoloaded/reloaded constant...

**Comment by timdiggins** [comment] 2016-11-19 23:18
Doing the same thing with a non-autoloaded path in the rails repo (/lib):

```ruby
# lib/some_library.rb
class SomeLibrary
  def tweet
    "chirp chirp"
  end
end
```

and adding `require 'some_library'` to the top of the posts controller
and similarly:

```
    @post.body = SomeLibrary.new.tweet
    # @post.body = SomeLibrary.new.tweet + " says the bird"
```
in the new action.

switching these around causes no problems.

So why? because reloading posts_controller.rb only reloads constants defined in posts_controller, not constants elsewhere. The requires are not then reloaded, but the constants are already pulled in. In fact changing the require statement to `LIB_WAS_REQUIRED = require 'some_library'` and outputting it shows a value of false. Alternatively just comment it out... it is fine, until you restart `rails s` altogether.

So then the question: why the problem you were having? Theory: I think because once you have a `require_dependency` for something NOT autoloaded/reloaded it can persist in some cache somewhere in rails loading and cause weirdness until you totally shut down and restart.

**Comment by timdiggins** [comment] 2016-11-19 23:19
Ok. Now it's really good-night!

**Comment by glebm** [comment] 2016-11-20 08:11
@timdiggins You're right, my conclusions about `require` getting unloaded are wrong.

I've made a dependency tracker to figure out what's going on in Thredded: https://gist.github.com/glebm/d63b36768bbc7f83127df7803cd321c5

Here is the output from the vanilla Rails app with `lib/some_library.rb` in your example.

Legend:

| Symbol | Explanation |
|---|---|
| `load_file` | Called on autoload / `require_dependency` only. |
| `+` | `WatchStack.new_constants` is called and returns these values. |
| last element in each load_file/require/load list | the result of the call, or the exception class if it failed. |

First load:

```s
(load_file "app/controllers/posts_controller.rb"  
  (require "some_library"    
    (+ SomeLibrary)
    true)
  (load_file "app/controllers/application_controller.rb"    
    (load_file "app/helpers/application_helper.rb"      
      (+ ApplicationHelper)
      true)
    (+ ApplicationController)
    true)
  (load_file "posts_helper.rb" LoadError)
  (+ PostsController)
  true)
```

After changing `posts_controller.rb`:

```s
(load_file "app/controllers/posts_controller.rb"  
  (require "some_library" false)
  (load_file "app/controllers/application_controller.rb"    
    (load_file "app/helpers/application_helper.rb"      
      (+ ApplicationHelper)
      true)
    (+ ApplicationController)
    true)
  (load_file "posts_helper.rb" LoadError)
  (+ PostsController)
  true)
```

**Comment by timdiggins** [comment] 2016-11-20 08:14
fantastic!

**Comment by glebm** [comment] 2016-11-20 08:29
So Thredded definitely has a problem, here is a snippet of the output when loading `/thredded` ([branch](https://github.com/thredded/thredded/tree/dependency-wat)):

```s
(load_file "~/repos/thredded/thredded/app/models/thredded/topic.rb"  
  (require "thredded/topics_search"    
    (require "thredded/search_parser" true)
    true)
  ( ... some Thredded load_file calls ... )
  ( ... some friendly_id requires ... )
  (+ Thredded::SearchParser Thredded::TopicsSearch Thredded::Topic)
  true)
```

So, `topic.rb` calls `require 'thredded/search_parser'`, same as the toy app call to `require 'some_library'` from `topics_controller.rb`.

However, `Thredded::SearchParser` is in the `+` for `topic.rb` instead of `search_parser.rb`!
All the constants on the same level as a `load_file` call are considered autoloaded, so this breaks.

Investigating why.

**Comment by glebm** [comment] 2016-11-20 08:35
OK, I know why but don't know how to fix it :(

The problem is that when loading `lib/thredded/search_parser.rb`, the watcher will check for the new constants in `Object` (not `Thredded`). `search_parser.rb` does not define any new constants in `Object` (it defines `Thredded` but that's not new).

**Comment by glebm** [comment] 2016-11-20 09:50
Opened an issue in `Rails` as it seems like a bug in ActiveSupport::Dependencies. Or perhaps we at least get some guidance if this is WAI.

**Comment by timdiggins** [comment] 2016-11-20 14:16
@glebm I've been doing a few tests with the dependencies_wat branch locally. I think the problem is with the **other** constants in all_view_hooks.rb (other than AllViewHooks). Two solutions I've found:

* move all of view_hooks into autoloading (this is fine, as the config is done within to_prepare).
* move each class into a separate file and use full constant naming.

Although it looks like SearchParser /TopicsSearch are equally problematic (they are put into autoloaded_constants when they aren't), reloading doesn't affect them (providing we do one of the above fixes). 

I'd propose doing **both** fixes -- it makes the code less surprising anyway.

It appears that rails autoloading only works (preserving non autoloaded references) for the constants that are defined **correctly** (ie. in their own named file). Not sure how this works.

**Comment by timdiggins** [comment] 2016-11-20 16:17
Ok @glebm what a saga. I got this wrong in my summary above. The only way I've found a solution is to make everything in view_hooks in an autoloaded path (the first bullet).

But I'm sure you're on the right path with it being a problem with the way ActiveSupport::Dependencies handles the namespacing modules (however moving the view_hooks/config and renderer out of the ViewHooks namespace didn't seem to solve the reloading issue).

**Comment by glebm** [comment] 2016-11-20 16:20
@timdiggins The SearchParser is not affected by reloading only because it isn't used other than on the search page. I do see a SearchParser error on the search page after a reload (after changing view hooks so that they don't error first):

![topic-search-dep](https://cloud.githubusercontent.com/assets/216339/20464303/13ed7866-af3d-11e6-8fa5-2223457bfad9.png)

**Comment by timdiggins** [comment] 2016-11-20 17:47
@glebm ok -- great. I now totally agree with what you wrote in https://github.com/rails/rails/issues/27119 😁

**Comment by glebm** [comment] 2016-11-23 00:54
I've remedied the situation in the three commits above for now, by moving TopicsSearch and SearchParser to `app/models/concerns`, using `Thredded::` to refer to Thredded constants everywhere, and removing one `require` from an autoloaded file.

As there is nothing more we can do on this here at the moment since it's a Rails bug, closing.

**Closed by glebm** 2016-11-23 00:54 UTC
