### ISSUE TITLE
Some words need to wrap with t function 

### ISSUE THREAD

**Issue by dava777** [thredded/thredded#544] opened 2017-03-09 20:16 UTC
Please, wrap words like "User" and "Moderation state" with "t" function in this [page](https://github.com/thredded/thredded/blob/master/app/views/thredded/moderation/users.html.erb)

**Comment by glebm** [comment] 2017-03-09 23:32
Feel free to send a PR.
Closing as duplicate of #62.

**Closed by glebm** 2017-03-09 23:32 UTC
